// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (
    user_id, media_id, status, rating, started_at, completed_at,
    rewatch_count, progress, total, note, contains_spoilers
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, user_id, media_id, status, rating, started_at, completed_at, rewatch_count, progress, total, note, contains_spoilers, created_at, updated_at
`

type CreateLogParams struct {
	UserID           pgtype.UUID
	MediaID          pgtype.UUID
	Status           string
	Rating           pgtype.Numeric
	StartedAt        pgtype.Date
	CompletedAt      pgtype.Date
	RewatchCount     pgtype.Int4
	Progress         pgtype.Int4
	Total            pgtype.Int4
	Note             pgtype.Text
	ContainsSpoilers pgtype.Bool
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, createLog,
		arg.UserID,
		arg.MediaID,
		arg.Status,
		arg.Rating,
		arg.StartedAt,
		arg.CompletedAt,
		arg.RewatchCount,
		arg.Progress,
		arg.Total,
		arg.Note,
		arg.ContainsSpoilers,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RewatchCount,
		&i.Progress,
		&i.Total,
		&i.Note,
		&i.ContainsSpoilers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLog = `-- name: DeleteLog :exec
DELETE FROM logs WHERE id = $1
`

func (q *Queries) DeleteLog(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLog, id)
	return err
}

const getLogByID = `-- name: GetLogByID :one
SELECT id, user_id, media_id, status, rating, started_at, completed_at, rewatch_count, progress, total, note, contains_spoilers, created_at, updated_at FROM logs WHERE id = $1
`

func (q *Queries) GetLogByID(ctx context.Context, id pgtype.UUID) (Log, error) {
	row := q.db.QueryRow(ctx, getLogByID, id)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RewatchCount,
		&i.Progress,
		&i.Total,
		&i.Note,
		&i.ContainsSpoilers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLogByUserAndMedia = `-- name: GetLogByUserAndMedia :one
SELECT id, user_id, media_id, status, rating, started_at, completed_at, rewatch_count, progress, total, note, contains_spoilers, created_at, updated_at FROM logs WHERE user_id = $1 AND media_id = $2
`

type GetLogByUserAndMediaParams struct {
	UserID  pgtype.UUID
	MediaID pgtype.UUID
}

func (q *Queries) GetLogByUserAndMedia(ctx context.Context, arg GetLogByUserAndMediaParams) (Log, error) {
	row := q.db.QueryRow(ctx, getLogByUserAndMedia, arg.UserID, arg.MediaID)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RewatchCount,
		&i.Progress,
		&i.Total,
		&i.Note,
		&i.ContainsSpoilers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimeline = `-- name: GetTimeline :many
SELECT l.id, l.user_id, l.media_id, l.status, l.rating, l.started_at, l.completed_at, l.rewatch_count, l.progress, l.total, l.note, l.contains_spoilers, l.created_at, l.updated_at, u.username, u.display_name FROM logs l
JOIN users u ON l.user_id = u.id
WHERE l.user_id IN (
    SELECT following_id FROM follows WHERE follower_id = $1
)
OR l.user_id = $1
ORDER BY l.created_at DESC
LIMIT $2 OFFSET $3
`

type GetTimelineParams struct {
	FollowerID pgtype.UUID
	Limit      int32
	Offset     int32
}

type GetTimelineRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	MediaID          pgtype.UUID
	Status           string
	Rating           pgtype.Numeric
	StartedAt        pgtype.Date
	CompletedAt      pgtype.Date
	RewatchCount     pgtype.Int4
	Progress         pgtype.Int4
	Total            pgtype.Int4
	Note             pgtype.Text
	ContainsSpoilers pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Username         string
	DisplayName      pgtype.Text
}

// Get logs from users that $1 follows
func (q *Queries) GetTimeline(ctx context.Context, arg GetTimelineParams) ([]GetTimelineRow, error) {
	rows, err := q.db.Query(ctx, getTimeline, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTimelineRow
	for rows.Next() {
		var i GetTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaID,
			&i.Status,
			&i.Rating,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RewatchCount,
			&i.Progress,
			&i.Total,
			&i.Note,
			&i.ContainsSpoilers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPublicActivity = `-- name: ListLatestPublicActivity :many
SELECT 
    l.id,
    l.media_id,
    l.status,
    l.rating,
    l.note,
    l.created_at,
    u.username,
    u.display_name,
    m.title,
    m.cover_image,
    m.type
FROM logs l
JOIN users u ON l.user_id = u.id
JOIN media m ON l.media_id = m.id
WHERE l.status = 'completed'
  AND u.is_public = true
ORDER BY l.created_at DESC
LIMIT $1 OFFSET $2
`

type ListLatestPublicActivityParams struct {
	Limit  int32
	Offset int32
}

type ListLatestPublicActivityRow struct {
	ID          pgtype.UUID
	MediaID     pgtype.UUID
	Status      string
	Rating      pgtype.Numeric
	Note        pgtype.Text
	CreatedAt   pgtype.Timestamptz
	Username    string
	DisplayName pgtype.Text
	Title       string
	CoverImage  pgtype.Text
	Type        string
}

func (q *Queries) ListLatestPublicActivity(ctx context.Context, arg ListLatestPublicActivityParams) ([]ListLatestPublicActivityRow, error) {
	rows, err := q.db.Query(ctx, listLatestPublicActivity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestPublicActivityRow
	for rows.Next() {
		var i ListLatestPublicActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Status,
			&i.Rating,
			&i.Note,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.Title,
			&i.CoverImage,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'completed') as completed_count,
    COUNT(*) FILTER (WHERE status = 'in_progress') as in_progress_count,
    COUNT(*) FILTER (WHERE status = 'planned') as planned_count,
    COUNT(*) FILTER (WHERE status = 'dropped') as dropped_count,
    COALESCE(AVG(rating) FILTER (WHERE rating IS NOT NULL), 0) as average_rating,
    COUNT(DISTINCT media_id) as total_media
FROM logs 
WHERE user_id = $1
`

type GetUserStatsRow struct {
	CompletedCount  int64
	InProgressCount int64
	PlannedCount    int64
	DroppedCount    int64
	AverageRating   float64
	TotalMedia      int64
}

func (q *Queries) GetUserStats(ctx context.Context, userID pgtype.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(
		&i.CompletedCount,
		&i.InProgressCount,
		&i.PlannedCount,
		&i.DroppedCount,
		&i.AverageRating,
		&i.TotalMedia,
	)
	return i, err
}

const listLogsByMedia = `-- name: ListLogsByMedia :many
SELECT l.id, l.user_id, l.media_id, l.status, l.rating, l.started_at, l.completed_at, l.rewatch_count, l.progress, l.total, l.note, l.contains_spoilers, l.created_at, l.updated_at, u.username, u.display_name FROM logs l
JOIN users u ON l.user_id = u.id
WHERE l.media_id = $1 AND l.status = 'completed'
ORDER BY l.rating DESC NULLS LAST, l.created_at DESC
LIMIT $2 OFFSET $3
`

type ListLogsByMediaParams struct {
	MediaID pgtype.UUID
	Limit   int32
	Offset  int32
}

type ListLogsByMediaRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	MediaID          pgtype.UUID
	Status           string
	Rating           pgtype.Numeric
	StartedAt        pgtype.Date
	CompletedAt      pgtype.Date
	RewatchCount     pgtype.Int4
	Progress         pgtype.Int4
	Total            pgtype.Int4
	Note             pgtype.Text
	ContainsSpoilers pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Username         string
	DisplayName      pgtype.Text
}

func (q *Queries) ListLogsByMedia(ctx context.Context, arg ListLogsByMediaParams) ([]ListLogsByMediaRow, error) {
	rows, err := q.db.Query(ctx, listLogsByMedia, arg.MediaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogsByMediaRow
	for rows.Next() {
		var i ListLogsByMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaID,
			&i.Status,
			&i.Rating,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RewatchCount,
			&i.Progress,
			&i.Total,
			&i.Note,
			&i.ContainsSpoilers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByUser = `-- name: ListLogsByUser :many
SELECT id, user_id, media_id, status, rating, started_at, completed_at, rewatch_count, progress, total, note, contains_spoilers, created_at, updated_at FROM logs 
WHERE user_id = $1 
AND (NULLIF($2::varchar, '') IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListLogsByUserParams struct {
	UserID  pgtype.UUID
	Column2 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListLogsByUser(ctx context.Context, arg ListLogsByUserParams) ([]Log, error) {
	rows, err := q.db.Query(ctx, listLogsByUser,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaID,
			&i.Status,
			&i.Rating,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RewatchCount,
			&i.Progress,
			&i.Total,
			&i.Note,
			&i.ContainsSpoilers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLog = `-- name: UpdateLog :one
UPDATE logs SET
    status = COALESCE($2, status),
    rating = COALESCE($3, rating),
    started_at = COALESCE($4, started_at),
    completed_at = COALESCE($5, completed_at),
    rewatch_count = COALESCE($6, rewatch_count),
    progress = COALESCE($7, progress),
    total = COALESCE($8, total),
    note = COALESCE($9, note),
    contains_spoilers = COALESCE($10, contains_spoilers),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, media_id, status, rating, started_at, completed_at, rewatch_count, progress, total, note, contains_spoilers, created_at, updated_at
`

type UpdateLogParams struct {
	ID               pgtype.UUID
	Status           string
	Rating           pgtype.Numeric
	StartedAt        pgtype.Date
	CompletedAt      pgtype.Date
	RewatchCount     pgtype.Int4
	Progress         pgtype.Int4
	Total            pgtype.Int4
	Note             pgtype.Text
	ContainsSpoilers pgtype.Bool
}

func (q *Queries) UpdateLog(ctx context.Context, arg UpdateLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, updateLog,
		arg.ID,
		arg.Status,
		arg.Rating,
		arg.StartedAt,
		arg.CompletedAt,
		arg.RewatchCount,
		arg.Progress,
		arg.Total,
		arg.Note,
		arg.ContainsSpoilers,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RewatchCount,
		&i.Progress,
		&i.Total,
		&i.Note,
		&i.ContainsSpoilers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
