// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMediaGenre = `-- name: AddMediaGenre :exec
INSERT INTO media_genres (media_id, genre_id) VALUES ($1, $2)
`

type AddMediaGenreParams struct {
	MediaID pgtype.UUID
	GenreID pgtype.UUID
}

func (q *Queries) AddMediaGenre(ctx context.Context, arg AddMediaGenreParams) error {
	_, err := q.db.Exec(ctx, addMediaGenre, arg.MediaID, arg.GenreID)
	return err
}

const createGenre = `-- name: CreateGenre :one
INSERT INTO genres (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRow(ctx, createGenre, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    type, title, original_title, description, cover_image,
    release_date, metadata, tmdb_id, mal_id, google_books_id, igdb_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, type, title, original_title, description, cover_image, release_date, metadata, tmdb_id, mal_id, google_books_id, igdb_id, created_at, updated_at
`

type CreateMediaParams struct {
	Type          string
	Title         string
	OriginalTitle pgtype.Text
	Description   pgtype.Text
	CoverImage    pgtype.Text
	ReleaseDate   pgtype.Date
	Metadata      []byte
	TmdbID        pgtype.Text
	MalID         pgtype.Int4
	GoogleBooksID pgtype.Text
	IgdbID        pgtype.Int4
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.Type,
		arg.Title,
		arg.OriginalTitle,
		arg.Description,
		arg.CoverImage,
		arg.ReleaseDate,
		arg.Metadata,
		arg.TmdbID,
		arg.MalID,
		arg.GoogleBooksID,
		arg.IgdbID,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Description,
		&i.CoverImage,
		&i.ReleaseDate,
		&i.Metadata,
		&i.TmdbID,
		&i.MalID,
		&i.GoogleBooksID,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMedia, id)
	return err
}

const getGenreByName = `-- name: GetGenreByName :one
SELECT id, name FROM genres WHERE name = $1
`

func (q *Queries) GetGenreByName(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRow(ctx, getGenreByName, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, type, title, original_title, description, cover_image, release_date, metadata, tmdb_id, mal_id, google_books_id, igdb_id, created_at, updated_at FROM media WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id pgtype.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Description,
		&i.CoverImage,
		&i.ReleaseDate,
		&i.Metadata,
		&i.TmdbID,
		&i.MalID,
		&i.GoogleBooksID,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaByTMDBID = `-- name: GetMediaByTMDBID :one
SELECT id, type, title, original_title, description, cover_image, release_date, metadata, tmdb_id, mal_id, google_books_id, igdb_id, created_at, updated_at FROM media WHERE tmdb_id = $1
`

func (q *Queries) GetMediaByTMDBID(ctx context.Context, tmdbID pgtype.Text) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByTMDBID, tmdbID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Description,
		&i.CoverImage,
		&i.ReleaseDate,
		&i.Metadata,
		&i.TmdbID,
		&i.MalID,
		&i.GoogleBooksID,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaGenres = `-- name: GetMediaGenres :many
SELECT g.id, g.name FROM genres g
JOIN media_genres mg ON g.id = mg.genre_id
WHERE mg.media_id = $1
`

func (q *Queries) GetMediaGenres(ctx context.Context, mediaID pgtype.UUID) ([]Genre, error) {
	rows, err := q.db.Query(ctx, getMediaGenres, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenres = `-- name: ListGenres :many
SELECT id, name FROM genres ORDER BY name
`

func (q *Queries) ListGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedia = `-- name: ListMedia :many
SELECT id, type, title, original_title, description, cover_image, release_date, metadata, tmdb_id, mal_id, google_books_id, igdb_id, created_at, updated_at FROM media 
WHERE (NULLIF($1::varchar, '') IS NULL OR type = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMediaParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMedia, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.OriginalTitle,
			&i.Description,
			&i.CoverImage,
			&i.ReleaseDate,
			&i.Metadata,
			&i.TmdbID,
			&i.MalID,
			&i.GoogleBooksID,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMediaGenre = `-- name: RemoveMediaGenre :exec
DELETE FROM media_genres WHERE media_id = $1 AND genre_id = $2
`

type RemoveMediaGenreParams struct {
	MediaID pgtype.UUID
	GenreID pgtype.UUID
}

func (q *Queries) RemoveMediaGenre(ctx context.Context, arg RemoveMediaGenreParams) error {
	_, err := q.db.Exec(ctx, removeMediaGenre, arg.MediaID, arg.GenreID)
	return err
}

const searchMedia = `-- name: SearchMedia :many
SELECT id, type, title, original_title, description, cover_image, release_date, metadata, tmdb_id, mal_id, google_books_id, igdb_id, created_at, updated_at FROM media 
WHERE (
    to_tsvector('english', title) @@ plainto_tsquery('english', $1)
    OR title ILIKE '%' || $1 || '%'
)
AND (NULLIF($2::varchar, '') IS NULL OR type = $2)
ORDER BY 
    CASE WHEN title ILIKE $1 || '%' THEN 0 ELSE 1 END,
    created_at DESC
LIMIT $3 OFFSET $4
`

type SearchMediaParams struct {
	Query  string
	Column2 string
	Limit  int32
	Offset int32
}

func (q *Queries) SearchMedia(ctx context.Context, arg SearchMediaParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, searchMedia,
		arg.Query,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.OriginalTitle,
			&i.Description,
			&i.CoverImage,
			&i.ReleaseDate,
			&i.Metadata,
			&i.TmdbID,
			&i.MalID,
			&i.GoogleBooksID,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedia = `-- name: UpdateMedia :one
UPDATE media SET
    title = COALESCE($2, title),
    original_title = COALESCE($3, original_title),
    description = COALESCE($4, description),
    cover_image = COALESCE($5, cover_image),
    release_date = COALESCE($6, release_date),
    metadata = COALESCE($7, metadata),
    updated_at = NOW()
WHERE id = $1
RETURNING id, type, title, original_title, description, cover_image, release_date, metadata, tmdb_id, mal_id, google_books_id, igdb_id, created_at, updated_at
`

type UpdateMediaParams struct {
	ID            pgtype.UUID
	Title         string
	OriginalTitle pgtype.Text
	Description   pgtype.Text
	CoverImage    pgtype.Text
	ReleaseDate   pgtype.Date
	Metadata      []byte
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMedia,
		arg.ID,
		arg.Title,
		arg.OriginalTitle,
		arg.Description,
		arg.CoverImage,
		arg.ReleaseDate,
		arg.Metadata,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Description,
		&i.CoverImage,
		&i.ReleaseDate,
		&i.Metadata,
		&i.TmdbID,
		&i.MalID,
		&i.GoogleBooksID,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
