// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	PasswordHash string
	DisplayName  pgtype.Text
	AvatarUrl    pgtype.Text
	Bio          pgtype.Text
	IsPublic     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
