// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (user_id, media_id, log_id, title, content, rating, contains_spoilers)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, media_id, log_id, title, content, rating, contains_spoilers, created_at, updated_at
`

type CreateReviewParams struct {
	UserID           pgtype.UUID
	MediaID          pgtype.UUID
	LogID            pgtype.UUID
	Title            pgtype.Text
	Content          string
	Rating           pgtype.Numeric
	ContainsSpoilers pgtype.Bool
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.UserID,
		arg.MediaID,
		arg.LogID,
		arg.Title,
		arg.Content,
		arg.Rating,
		arg.ContainsSpoilers,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaID,
		&i.LogID,
		&i.Title,
		&i.Content,
		&i.Rating,
		&i.ContainsSpoilers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, user_id, media_id, log_id, title, content, rating, contains_spoilers, created_at, updated_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id pgtype.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaID,
		&i.LogID,
		&i.Title,
		&i.Content,
		&i.Rating,
		&i.ContainsSpoilers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByLog = `-- name: GetReviewByLog :one
SELECT id, user_id, media_id, log_id, title, content, rating, contains_spoilers, created_at, updated_at FROM reviews WHERE log_id = $1
`

func (q *Queries) GetReviewByLog(ctx context.Context, logID pgtype.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByLog, logID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaID,
		&i.LogID,
		&i.Title,
		&i.Content,
		&i.Rating,
		&i.ContainsSpoilers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewsByMedia = `-- name: ListReviewsByMedia :many
SELECT r.id, r.user_id, r.media_id, r.log_id, r.title, r.content, r.rating, r.contains_spoilers, r.created_at, r.updated_at, u.username, u.display_name 
FROM reviews r
JOIN users u ON r.user_id = u.id
WHERE r.media_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReviewsByMediaParams struct {
	MediaID pgtype.UUID
	Limit   int32
	Offset  int32
}

type ListReviewsByMediaRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	MediaID          pgtype.UUID
	LogID            pgtype.UUID
	Title            pgtype.Text
	Content          string
	Rating           pgtype.Numeric
	ContainsSpoilers pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Username         string
	DisplayName      pgtype.Text
}

func (q *Queries) ListReviewsByMedia(ctx context.Context, arg ListReviewsByMediaParams) ([]ListReviewsByMediaRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByMedia, arg.MediaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByMediaRow
	for rows.Next() {
		var i ListReviewsByMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaID,
			&i.LogID,
			&i.Title,
			&i.Content,
			&i.Rating,
			&i.ContainsSpoilers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUser = `-- name: ListReviewsByUser :many
SELECT id, user_id, media_id, log_id, title, content, rating, contains_spoilers, created_at, updated_at FROM reviews WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListReviewsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListReviewsByUser(ctx context.Context, arg ListReviewsByUserParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaID,
			&i.LogID,
			&i.Title,
			&i.Content,
			&i.Rating,
			&i.ContainsSpoilers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews SET
    title = COALESCE($2, title),
    content = COALESCE($3, content),
    rating = COALESCE($4, rating),
    contains_spoilers = COALESCE($5, contains_spoilers),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, media_id, log_id, title, content, rating, contains_spoilers, created_at, updated_at
`

type UpdateReviewParams struct {
	ID               pgtype.UUID
	Title            pgtype.Text
	Content          string
	Rating           pgtype.Numeric
	ContainsSpoilers pgtype.Bool
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Rating,
		arg.ContainsSpoilers,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaID,
		&i.LogID,
		&i.Title,
		&i.Content,
		&i.Rating,
		&i.ContainsSpoilers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
