// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: social.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM follows WHERE following_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followingID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, followingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM follows WHERE follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, followerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLikesForLog = `-- name: CountLikesForLog :one
SELECT COUNT(*) FROM likes WHERE log_id = $1
`

func (q *Queries) CountLikesForLog(ctx context.Context, logID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLikesForLog, logID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLikesForReview = `-- name: CountLikesForReview :one
SELECT COUNT(*) FROM likes WHERE review_id = $1
`

func (q *Queries) CountLikesForReview(ctx context.Context, reviewID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLikesForReview, reviewID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFollow = `-- name: CreateFollow :one
INSERT INTO follows (follower_id, following_id) VALUES ($1, $2) RETURNING id, follower_id, following_id, created_at
`

type CreateFollowParams struct {
	FollowerID  pgtype.UUID
	FollowingID pgtype.UUID
}

// Follow queries
func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) (Follow, error) {
	row := q.db.QueryRow(ctx, createFollow, arg.FollowerID, arg.FollowingID)
	var i Follow
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FollowingID,
		&i.CreatedAt,
	)
	return i, err
}

const createLike = `-- name: CreateLike :one
INSERT INTO likes (user_id, log_id, review_id) VALUES ($1, $2, $3) RETURNING id, user_id, log_id, review_id, created_at
`

type CreateLikeParams struct {
	UserID   pgtype.UUID
	LogID    pgtype.UUID
	ReviewID pgtype.UUID
}

// Like queries
func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.db.QueryRow(ctx, createLike, arg.UserID, arg.LogID, arg.ReviewID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogID,
		&i.ReviewID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM follows WHERE follower_id = $1 AND following_id = $2
`

type DeleteFollowParams struct {
	FollowerID  pgtype.UUID
	FollowingID pgtype.UUID
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.Exec(ctx, deleteFollow, arg.FollowerID, arg.FollowingID)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes WHERE user_id = $1 AND ((log_id = $2) OR (review_id = $3))
`

type DeleteLikeParams struct {
	UserID   pgtype.UUID
	LogID    pgtype.UUID
	ReviewID pgtype.UUID
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike, arg.UserID, arg.LogID, arg.ReviewID)
	return err
}

const getFollow = `-- name: GetFollow :one
SELECT id, follower_id, following_id, created_at FROM follows WHERE follower_id = $1 AND following_id = $2
`

type GetFollowParams struct {
	FollowerID  pgtype.UUID
	FollowingID pgtype.UUID
}

func (q *Queries) GetFollow(ctx context.Context, arg GetFollowParams) (Follow, error) {
	row := q.db.QueryRow(ctx, getFollow, arg.FollowerID, arg.FollowingID)
	var i Follow
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FollowingID,
		&i.CreatedAt,
	)
	return i, err
}

const getLikeByLog = `-- name: GetLikeByLog :one
SELECT id, user_id, log_id, review_id, created_at FROM likes WHERE user_id = $1 AND log_id = $2
`

type GetLikeByLogParams struct {
	UserID pgtype.UUID
	LogID  pgtype.UUID
}

func (q *Queries) GetLikeByLog(ctx context.Context, arg GetLikeByLogParams) (Like, error) {
	row := q.db.QueryRow(ctx, getLikeByLog, arg.UserID, arg.LogID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogID,
		&i.ReviewID,
		&i.CreatedAt,
	)
	return i, err
}

const getLikeByReview = `-- name: GetLikeByReview :one
SELECT id, user_id, log_id, review_id, created_at FROM likes WHERE user_id = $1 AND review_id = $2
`

type GetLikeByReviewParams struct {
	UserID   pgtype.UUID
	ReviewID pgtype.UUID
}

func (q *Queries) GetLikeByReview(ctx context.Context, arg GetLikeByReviewParams) (Like, error) {
	row := q.db.QueryRow(ctx, getLikeByReview, arg.UserID, arg.ReviewID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogID,
		&i.ReviewID,
		&i.CreatedAt,
	)
	return i, err
}

const hasUserLikedLog = `-- name: HasUserLikedLog :one
SELECT EXISTS(SELECT 1 FROM likes WHERE user_id = $1 AND log_id = $2)
`

type HasUserLikedLogParams struct {
	UserID pgtype.UUID
	LogID  pgtype.UUID
}

func (q *Queries) HasUserLikedLog(ctx context.Context, arg HasUserLikedLogParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedLog, arg.UserID, arg.LogID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasUserLikedReview = `-- name: HasUserLikedReview :one
SELECT EXISTS(SELECT 1 FROM likes WHERE user_id = $1 AND review_id = $2)
`

type HasUserLikedReviewParams struct {
	UserID   pgtype.UUID
	ReviewID pgtype.UUID
}

func (q *Queries) HasUserLikedReview(ctx context.Context, arg HasUserLikedReviewParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedReview, arg.UserID, arg.ReviewID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM follows WHERE follower_id = $1 AND following_id = $2
)
`

type IsFollowingParams struct {
	FollowerID  pgtype.UUID
	FollowingID pgtype.UUID
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.username, u.email, u.password_hash, u.display_name, u.avatar_url, u.bio, u.is_public, u.created_at, u.updated_at FROM users u
JOIN follows f ON u.id = f.follower_id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowersParams struct {
	FollowingID pgtype.UUID
	Limit       int32
	Offset      int32
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listFollowers, arg.FollowingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.username, u.email, u.password_hash, u.display_name, u.avatar_url, u.bio, u.is_public, u.created_at, u.updated_at FROM users u
JOIN follows f ON u.id = f.following_id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowingParams struct {
	FollowerID pgtype.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listFollowing, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
