// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: test.sql

package db

import (
	"context"
)

const testConnection = `-- name: TestConnection :one
SELECT 1 as connected
`

func (q *Queries) TestConnection(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, testConnection)
	var connected int32
	err := row.Scan(&connected)
	return connected, err
}
